name: Manual Hello World

on:
  workflow_dispatch:  # Enables manual trigger

jobs:
  run-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # or whatever version you use

      - name: Run Hello World
        run: node index.js
